# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00241c545277d934ef583077da1e44ebf44c523bf55e7ef48fadff1d8cfca590f0a9ce6fcad733e88727401240e6297631e1d14111dc05be77d5f05bce2cfe27

test:
  secret_key_base: 3f34cda73d1cfa2b8d96e4064302ef51296cf9c9e0d51d1f3a975fa610e71e9e1982333164582df916e32c5cde98407e88cc19e933b2657e472ebbe1211d6840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
